---
title: "Project 1"
author: "Jasmine Anand"
date: "May 08, 2021"
output:
  html_document:
    toc: true
    toc_float:
      collapsed: false
---



<div id="introduction" class="section level2">
<h2>Introduction</h2>
<div id="i-decided-to-work-with-two-marvel-datasets-because-i-am-a-huge-marvel-fan.-i-have-watched-all-the-marvel-movies-at-least-3-times-and-have-also-read-a-lot-of-the-marvel-comic-books.-through-this-projct-i-wanted-to-see-if-i-can-find-any-associations-through-the-datasets-i-have-chosen.-for-this-project-i-will-be-analyzing-2-different-marvel-datasets.-the-first-dataset-called-stats-has-information-on-abilities-of-each-of-the-marvel-characters-such-as-intelligence-strength-power-and-speed.-most-of-these-abilities-range-from-1-to-100-except-for-intelligence-and-durability.-there-is-a-total-column-in-this-dataset-which-adds-up-all-of-the-values-from-the-other-numerical-columns.-this-dataset-also-contains-information-on-whether-or-not-the-character-is-good-or-bad.-the-second-dataset-called-character_info-contains-information-on-physical-attributes-of-the-marvel-characters-such-as-eye-color-race-gender-hair-color-height-and-weight.-the-height-is-in-centimeters-and-weight-is-in-kilograms.-this-dataset-also-contains-whether-the-character-is-bad-or-good.-i-found-both-of-these-datasets-while-doing-a-google-search-on-marvel-datasets.-these-were-both-found-on-a-website-called-kaggle-and-the-owner-of-these-datasets-is-daniel-r.-i-do-not-know-what-to-expect-from-this-dataset.-i-hope-there-will-be-some-relationship-between-a-characters-alignment-good-or-bad-and-their-other-characteristics-like-power-speed-height-weight-etc." class="section level5">
<h5>I decided to work with two Marvel datasets because I am a huge Marvel fan. I have watched all the Marvel movies at least 3 times and have also read a lot of the Marvel comic books. Through this projct I wanted to see if I can find any associations through the datasets I have chosen. For this Project, I will be analyzing 2 different Marvel datasets. The first dataset, called stats, has information on abilities of each of the Marvel Characters, such as intelligence, strength, power, and speed. Most of these abilities range from 1 to 100, except for Intelligence and Durability. There is a Total column in this dataset, which adds up all of the values from the other numerical columns. This dataset also contains information on whether or not the character is good or bad. The second dataset, called character_info, contains information on physical attributes of the Marvel Characters, such as eye color, race, gender, hair color, height, and weight. The height is in centimeters and weight is in kilograms. This dataset also contains whether the character is bad or good. I found both of these datasets while doing a google search on marvel datasets. These were both found on a website called kaggle and the owner of these datasets is Daniel R. I do not know what to expect from this dataset. I hope there will be some relationship between a character’s alignment (good or bad) and their other characteristics like power, speed, height, weight, etc.</h5>
<pre class="r"><code>library(tidyverse)
library(dplyr)

stats &lt;- read.csv(&quot;charcters_stats.csv&quot;)
character_info &lt;- read.csv(&quot;marvel_characters_info.csv&quot;)

glimpse(stats)</code></pre>
<pre><code>## Rows: 611
## Columns: 9
## $ Name         &lt;fct&gt; 3-D Man, A-Bomb, Abe Sapien, Abin Sur, Abomination, Abra…
## $ Alignment    &lt;fct&gt; good, good, good, good, bad, bad, good, good, good, good…
## $ Intelligence &lt;int&gt; 50, 38, 88, 50, 63, 88, 63, 1, 1, 10, 75, 50, 63, 1, 63,…
## $ Strength     &lt;int&gt; 31, 100, 14, 90, 80, 100, 10, 1, 1, 8, 28, 85, 80, 1, 10…
## $ Speed        &lt;int&gt; 43, 17, 35, 53, 53, 83, 12, 1, 1, 13, 38, 100, 23, 1, 17…
## $ Durability   &lt;int&gt; 32, 80, 42, 64, 90, 99, 100, 1, 1, 5, 80, 85, 90, 1, 10,…
## $ Power        &lt;int&gt; 25, 17, 35, 84, 55, 100, 71, 0, 0, 5, 72, 100, 98, 0, 7,…
## $ Combat       &lt;int&gt; 52, 64, 85, 65, 95, 56, 64, 1, 1, 20, 95, 40, 32, 1, 55,…
## $ Total        &lt;int&gt; 233, 316, 299, 406, 436, 526, 320, 5, 5, 61, 388, 460, 3…</code></pre>
<pre class="r"><code>glimpse(character_info)</code></pre>
<pre><code>## Rows: 734
## Columns: 11
## $ ID        &lt;int&gt; 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 1…
## $ Name      &lt;fct&gt; A-Bomb, Abe Sapien, Abin Sur, Abomination, Abraxas, Absorbi…
## $ Alignment &lt;fct&gt; good, good, good, bad, bad, bad, good, good, good, good, go…
## $ Gender    &lt;fct&gt; Male, Male, Male, Male, Male, Male, Male, Male, Female, Mal…
## $ EyeColor  &lt;fct&gt; yellow, blue, blue, green, blue, blue, blue, blue, blue, br…
## $ Race      &lt;fct&gt; Human, Icthyo Sapien, Ungaran, Human / Radiation, Cosmic En…
## $ HairColor &lt;fct&gt; No Hair, No Hair, No Hair, No Hair, Black, No Hair, Blond, …
## $ Publisher &lt;fct&gt; Marvel Comics, Dark Horse Comics, DC Comics, Marvel Comics,…
## $ SkinColor &lt;fct&gt; -, blue, red, -, -, -, -, -, -, -, -, -, -, -, -, -, -, bla…
## $ Height    &lt;dbl&gt; 203, 191, 185, 203, -99, 193, -99, 185, 173, 178, 191, 188,…
## $ Weight    &lt;int&gt; 441, 65, 90, 441, -99, 122, -99, 88, 61, 81, 104, 108, 90, …</code></pre>
</div>
</div>
<div id="tidying-the-data" class="section level2">
<h2>Tidying the data!</h2>
<div id="looking-through-both-of-the-datasets-i-saw-that-the-stat-dataset-looked-complete-but-the-character_info-dataset-required-a-little-bit-of-cleaning.-for-instance-i-am-going-to-remove-the-skin-color-column-because-there-were-a-lot-of-missing-values-in-that-column.-i-am-also-saw-that-height-and-weight-had-some-values-of--99-which-most-likely-represent-missing-data.-for-these-values-i-am-just-going-to-omit-them-from-the-dataset." class="section level4">
<h4>Looking through both of the datasets, I saw that the stat dataset looked complete but the character_info dataset required a little bit of cleaning. For instance, I am going to remove the skin color column because there were a lot of missing values in that column. I am also saw that Height and Weight had some values of -99, which most likely represent missing data. For these values, I am just going to omit them from the dataset.</h4>
<pre class="r"><code>character_info &lt;- character_info %&gt;% select(-SkinColor) %&gt;% filter(Height != 
    -99) %&gt;% filter(Weight != -99)</code></pre>
<div id="since-both-of-the-datasets-are-already-tidy-i-will-make-them-untidy-with-a-pivot_longer-and-then-tidy-them-back-up-with-pivot_wider.-i-did-this-with-the-character_info-dataset.-i-am-first-doing-a-pivot_longer-on-the-columns-that-represent-some-sort-of-color-such-as-eye-colore-hair-color-and-skin-color.-then-i-am-going-to-do-a-pivot-wider-on-the-newly-created-column-named-body_part-to-tidy-the-dataset-again." class="section level5">
<h5>Since both of the datasets are already tidy, I will make them untidy with a pivot_longer and then tidy them back up with pivot_wider. I did this with the character_info dataset. I am first doing a pivot_longer on the columns that represent some sort of color, such as eye colore, hair color, and skin color. Then I am going to do a pivot wider on the newly created column, named “Body_part”, to tidy the dataset again.</h5>
<pre class="r"><code>character_info &lt;- character_info %&gt;% pivot_longer(contains(&quot;Color&quot;), 
    names_to = &quot;Body_part&quot;, values_to = &quot;Color&quot;)

head(character_info, 10)  #untidy</code></pre>
<pre><code>## # A tibble: 10 x 10
##       ID Name   Alignment Gender Race    Publisher Height Weight Body_part Color
##    &lt;int&gt; &lt;fct&gt;  &lt;fct&gt;     &lt;fct&gt;  &lt;fct&gt;   &lt;fct&gt;      &lt;dbl&gt;  &lt;int&gt; &lt;chr&gt;     &lt;fct&gt;
##  1     0 A-Bomb good      Male   Human   Marvel C…    203    441 EyeColor  yell…
##  2     0 A-Bomb good      Male   Human   Marvel C…    203    441 HairColor No H…
##  3     1 Abe S… good      Male   Icthyo… Dark Hor…    191     65 EyeColor  blue 
##  4     1 Abe S… good      Male   Icthyo… Dark Hor…    191     65 HairColor No H…
##  5     2 Abin … good      Male   Ungaran DC Comics    185     90 EyeColor  blue 
##  6     2 Abin … good      Male   Ungaran DC Comics    185     90 HairColor No H…
##  7     3 Abomi… bad       Male   Human … Marvel C…    203    441 EyeColor  green
##  8     3 Abomi… bad       Male   Human … Marvel C…    203    441 HairColor No H…
##  9     5 Absor… bad       Male   Human   Marvel C…    193    122 EyeColor  blue 
## 10     5 Absor… bad       Male   Human   Marvel C…    193    122 HairColor No H…</code></pre>
</div>
<div id="the-following-pivot_wider-will-tidy-back-the-dataset-so-that-it-looks-like-the-original." class="section level5">
<h5>The following pivot_wider will tidy back the dataset, so that it looks like the original.</h5>
<pre class="r"><code>character_info &lt;- character_info %&gt;% pivot_wider(names_from = &quot;Body_part&quot;, 
    values_from = &quot;Color&quot;)  #tidy
head(character_info, 10)</code></pre>
<pre><code>## # A tibble: 10 x 10
##       ID Name  Alignment Gender Race  Publisher Height Weight EyeColor HairColor
##    &lt;int&gt; &lt;fct&gt; &lt;fct&gt;     &lt;fct&gt;  &lt;fct&gt; &lt;fct&gt;      &lt;dbl&gt;  &lt;int&gt; &lt;fct&gt;    &lt;fct&gt;    
##  1     0 A-Bo… good      Male   Human Marvel C…    203    441 yellow   No Hair  
##  2     1 Abe … good      Male   Icth… Dark Hor…    191     65 blue     No Hair  
##  3     2 Abin… good      Male   Unga… DC Comics    185     90 blue     No Hair  
##  4     3 Abom… bad       Male   Huma… Marvel C…    203    441 green    No Hair  
##  5     5 Abso… bad       Male   Human Marvel C…    193    122 blue     No Hair  
##  6     7 Adam… good      Male   Human DC Comics    185     88 blue     Blond    
##  7     8 Agen… good      Female -     Marvel C…    173     61 blue     Blond    
##  8     9 Agen… good      Male   Human Marvel C…    178     81 brown    Brown    
##  9    10 Agen… good      Male   -     Marvel C…    191    104 -        -        
## 10    11 Air-… bad       Male   -     Marvel C…    188    108 blue     White</code></pre>
</div>
</div>
</div>
<div id="joining-the-datasets" class="section level2">
<h2>Joining the datasets!</h2>
<div id="i-will-be-doing-an-inner-join-on-these-two-datasets.-i-want-to-only-keep-the-characters-that-are-common-between-the-two-datasets-because-i-want-each-character-to-have-all-the-attribute-information.-doing-any-other-join-such-as-a-full-join-or-left-join-would-have-left-me-with-characters-with-missing-information.-before-joining-the-datasets-i-removed-the-alignment-column-from-the-character_info-dataset-because-there-was-an-alignment-column-in-the-stats-dataset-and-this-would-give-us-duplicate-information.-i-also-removed-the-character-id-as-it-does-not-give-us-any-relevant-information-about-the-character." class="section level5">
<h5>I will be doing an inner join on these two datasets. I want to only keep the characters that are common between the two datasets because I want each character to have all the attribute information. Doing any other join, such as a full join or left join, would have left me with characters with missing information. Before joining the datasets, I removed the Alignment column from the character_info dataset because there was an Alignment column in the stats dataset, and this would give us duplicate information. I also removed the character ID as it does not give us any relevant information about the character.</h5>
<pre class="r"><code>character_info &lt;- character_info %&gt;% select(-Alignment, -ID)
character &lt;- inner_join(character_info, stats, by = &quot;Name&quot;)
character &lt;- character %&gt;% distinct_at(vars(Name), .keep_all = TRUE)

dim(stats)</code></pre>
<pre><code>## [1] 611   9</code></pre>
<pre class="r"><code>dim(character_info)</code></pre>
<pre><code>## [1] 490   8</code></pre>
<pre class="r"><code>dim(character)</code></pre>
<pre><code>## [1] 409  16</code></pre>
<pre class="r"><code>glimpse(character)</code></pre>
<pre><code>## Rows: 409
## Columns: 16
## $ Name         &lt;fct&gt; A-Bomb, Abe Sapien, Abin Sur, Abomination, Adam Strange,…
## $ Gender       &lt;fct&gt; Male, Male, Male, Male, Male, Male, Male, Male, Male, Ma…
## $ Race         &lt;fct&gt; Human, Icthyo Sapien, Ungaran, Human / Radiation, Human,…
## $ Publisher    &lt;fct&gt; Marvel Comics, Dark Horse Comics, DC Comics, Marvel Comi…
## $ Height       &lt;dbl&gt; 203, 191, 185, 203, 185, 178, 191, 188, 180, 178, 257, 1…
## $ Weight       &lt;int&gt; 441, 65, 90, 441, 88, 81, 104, 108, 90, 72, 173, 101, 68…
## $ EyeColor     &lt;fct&gt; yellow, blue, blue, green, blue, brown, -, blue, blue, b…
## $ HairColor    &lt;fct&gt; No Hair, No Hair, No Hair, No Hair, Blond, Brown, -, Whi…
## $ Alignment    &lt;fct&gt; good, good, good, bad, good, good, good, bad, good, good…
## $ Intelligence &lt;int&gt; 38, 88, 50, 63, 1, 10, 75, 50, 63, 63, 75, 1, 63, 38, 56…
## $ Strength     &lt;int&gt; 100, 14, 90, 80, 1, 8, 28, 85, 80, 10, 100, 1, 13, 10, 4…
## $ Speed        &lt;int&gt; 17, 35, 53, 53, 1, 13, 38, 100, 23, 17, 100, 1, 46, 28, …
## $ Durability   &lt;int&gt; 80, 42, 64, 90, 1, 5, 80, 85, 90, 10, 100, 1, 64, 28, 85…
## $ Power        &lt;int&gt; 17, 35, 84, 55, 0, 5, 72, 100, 98, 7, 100, 0, 17, 46, 73…
## $ Combat       &lt;int&gt; 64, 85, 65, 95, 1, 20, 95, 40, 32, 55, 100, 1, 42, 60, 8…
## $ Total        &lt;int&gt; 316, 299, 406, 436, 5, 61, 388, 460, 386, 162, 575, 5, 2…</code></pre>
</div>
<div id="the-character_info-dataset-had-409-observationscharacters-while-the-stats-dataset-had-611-observations.-since-the-resulting-joined-table-contained-490-observations-there-had-to-be-some-observations-that-were-dropped-from-both-datasets.-also-after-combining-the-two-datasets-i-removed-all-of-the-names-that-were-duplicate-and-that-got-rid-of-some-of-the-observations-as-well.-these-are-the-observations-dropped-from-the-stats-dataset" class="section level4">
<h4>The character_info dataset had 409 observations/characters, while the stats dataset had 611 observations. Since the resulting joined table contained 490 observations, there had to be some observations that were dropped from both datasets. Also, after combining the two datasets, I removed all of the names that were duplicate and that got rid of some of the observations as well. These are the observations dropped from the stats dataset:</h4>
<pre class="r"><code>setdiff(stats$Name, character$Name)</code></pre>
<pre><code>##   [1] &quot;3-D Man&quot;          &quot;Abraxas&quot;          &quot;Adam Monroe&quot;     
##   [4] &quot;Agent  13&quot;        &quot;Alex Woolsly&quot;     &quot;Allan Quatermain&quot;
##   [7] &quot;Ando Masahashi&quot;   &quot;Angela&quot;           &quot;Anti-Monitor&quot;    
##  [10] &quot;Anti-Spawn&quot;       &quot;Aquababy&quot;         &quot;Arsenal&quot;         
##  [13] &quot;Astro Boy&quot;        &quot;Atom I&quot;           &quot;Atom III&quot;        
##  [16] &quot;Atom IV&quot;          &quot;Azrael&quot;           &quot;Aztar&quot;           
##  [19] &quot;Batgirl I&quot;        &quot;Batgirl II&quot;       &quot;Batgirl III&quot;     
##  [22] &quot;Batgirl V&quot;        &quot;Beetle&quot;           &quot;Ben 10&quot;          
##  [25] &quot;Beyonder&quot;         &quot;Big Daddy&quot;        &quot;Bill Harken&quot;     
##  [28] &quot;Billy Kincaid&quot;    &quot;Bird-Brain&quot;       &quot;Bird-Man&quot;        
##  [31] &quot;Bird-Man II&quot;      &quot;Birdman&quot;          &quot;Black Abbott&quot;    
##  [34] &quot;Black Canary I&quot;   &quot;Black Canary II&quot;  &quot;Black Goliath&quot;   
##  [37] &quot;Blaquesmith&quot;      &quot;Blizzard&quot;         &quot;Blizzard I&quot;      
##  [40] &quot;Bloodhawk&quot;        &quot;Bloodwraith&quot;      &quot;Blue Beetle&quot;     
##  [43] &quot;Blue Beetle I&quot;    &quot;Blue Beetle III&quot;  &quot;Bolt&quot;            
##  [46] &quot;Bomb Queen&quot;       &quot;Boom Boom&quot;        &quot;Boomer&quot;          
##  [49] &quot;Box&quot;              &quot;Box IV&quot;           &quot;Bumbleboy&quot;       
##  [52] &quot;Bushido&quot;          &quot;Cameron Hicks&quot;    &quot;Captain Epic&quot;    
##  [55] &quot;Captain Planet&quot;   &quot;Captain Universe&quot; &quot;Cat II&quot;          
##  [58] &quot;Cerebra&quot;          &quot;Chameleon&quot;        &quot;Cheetah I&quot;       
##  [61] &quot;Chuck Norris&quot;     &quot;Claire Bennet&quot;    &quot;Clea&quot;            
##  [64] &quot;Cogliostro&quot;       &quot;Colin Wagner&quot;     &quot;Colossal Boy&quot;    
##  [67] &quot;Crimson Crusader&quot; &quot;Crimson Dynamo I&quot; &quot;Curse&quot;           
##  [70] &quot;Cy-Gor&quot;           &quot;Cyborg Superman&quot;  &quot;Danny Cooper&quot;    
##  [73] &quot;Daphne Powell&quot;    &quot;Darkman&quot;          &quot;Darkside&quot;        
##  [76] &quot;DL Hawkins&quot;       &quot;Dormammu&quot;         &quot;Dr Manhattan&quot;    
##  [79] &quot;Ego&quot;              &quot;Elle Bishop&quot;      &quot;Energy&quot;          
##  [82] &quot;ERG-1&quot;            &quot;Fallen One II&quot;    &quot;Faora&quot;           
##  [85] &quot;Fighting Spirit&quot;  &quot;Fixer&quot;            &quot;Flash Gordon&quot;    
##  [88] &quot;Flash I&quot;          &quot;Garbage Man&quot;      &quot;Gary Bell&quot;       
##  [91] &quot;General Zod&quot;      &quot;Ghost Rider II&quot;   &quot;Giant-Man&quot;       
##  [94] &quot;Giant-Man II&quot;     &quot;Gog&quot;              &quot;Goliath&quot;         
##  [97] &quot;Goliath II&quot;       &quot;Goliath III&quot;      &quot;Guardian&quot;        
## [100] &quot;Hancock&quot;         
##  [ reached getOption(&quot;max.print&quot;) -- omitted 101 entries ]</code></pre>
</div>
<div id="these-are-the-observations-dropped-from-the-character_info-dataset" class="section level4">
<h4>These are the observations dropped from the character_info dataset</h4>
<pre class="r"><code>setdiff(character_info$Name, character$Name)</code></pre>
<pre><code>##  [1] &quot;Absorbing Man&quot;      &quot;Agent 13&quot;           &quot;Ajax&quot;              
##  [4] &quot;Alien&quot;              &quot;Angel Dust&quot;         &quot;Ardina&quot;            
##  [7] &quot;Batgirl&quot;            &quot;Black Canary&quot;       &quot;Black Manta&quot;       
## [10] &quot;Boom-Boom&quot;          &quot;Buffy&quot;              &quot;Cheetah&quot;           
## [13] &quot;Citizen Steel&quot;      &quot;Clock King&quot;         &quot;Copycat&quot;           
## [16] &quot;Cottonmouth&quot;        &quot;Crimson Dynamo&quot;     &quot;Darth Vader&quot;       
## [19] &quot;Diamondback&quot;        &quot;Drax the Destroyer&quot; &quot;Enchantress&quot;       
## [22] &quot;Etrigan&quot;            &quot;Evil Deadpool&quot;      &quot;Flash&quot;             
## [25] &quot;Gamora&quot;             &quot;Gladiator&quot;          &quot;Gorilla Grodd&quot;     
## [28] &quot;Han Solo&quot;           &quot;Hawkwoman&quot;          &quot;Heat Wave&quot;         
## [31] &quot;Hela&quot;               &quot;Hybrid&quot;             &quot;Indiana Jones&quot;     
## [34] &quot;Jack-Jack&quot;          &quot;James T. Kirk&quot;      &quot;Jessica Jones&quot;     
## [37] &quot;Karate Kid&quot;         &quot;Kyle Rayner&quot;        &quot;Legion&quot;            
## [40] &quot;Luke Skywalker&quot;     &quot;Mantis&quot;             &quot;Mockingbird&quot;       
## [43] &quot;MODOK&quot;              &quot;Mr Immortal&quot;        &quot;Mysterio&quot;          
## [46] &quot;Nebula&quot;             &quot;Odin&quot;               &quot;One Punch Man&quot;     
## [49] &quot;Oracle&quot;             &quot;Paul Blart&quot;         &quot;Plantman&quot;          
## [52] &quot;Polaris&quot;            &quot;Predator&quot;           &quot;Professor Zoom&quot;    
## [55] &quot;Purple Man&quot;         &quot;Rambo&quot;              &quot;Ray&quot;               
## [58] &quot;Robin&quot;              &quot;Shadow Lass&quot;        &quot;Spider-Gwen&quot;       
## [61] &quot;Spock&quot;              &quot;Star-Lord&quot;          &quot;Static&quot;            
## [64] &quot;Steppenwolf&quot;        &quot;Swarm&quot;              &quot;T-1000&quot;            
## [67] &quot;Taskmaster&quot;         &quot;Triton&quot;             &quot;Vegeta&quot;            
## [70] &quot;Vibe&quot;               &quot;Violet Parr&quot;        &quot;Vixen&quot;             
## [73] &quot;Yoda&quot;</code></pre>
</div>
</div>
<div id="wrangling" class="section level2">
<h2>Wrangling!</h2>
<div id="using-all-6-core-dplyr-functions" class="section level3">
<h3>Using all 6 core dplyr functions</h3>
<div id="grabbing-all-of-the-females-and-sorting-them-based-on-power-and-intelligence" class="section level5">
<h5>Grabbing all of the females and sorting them based on Power and Intelligence</h5>
<pre class="r"><code>character %&gt;% filter(Gender == &quot;Female&quot;) %&gt;% arrange(desc(Power), 
    desc(Intelligence)) %&gt;% select(Name, Gender, Power, Intelligence)</code></pre>
<pre><code>## # A tibble: 116 x 4
##    Name         Gender Power Intelligence
##    &lt;fct&gt;        &lt;fct&gt;  &lt;int&gt;        &lt;int&gt;
##  1 Jean Grey    Female   100          100
##  2 Phoenix      Female   100          100
##  3 Thor Girl    Female   100           75
##  4 Zatanna      Female   100           75
##  5 Marvel Girl  Female   100           63
##  6 Miss Martian Female   100           63
##  7 Firebird     Female    90           38
##  8 Hope Summers Female    89           63
##  9 Storm        Female    88           75
## 10 Supergirl    Female    85           94
## # … with 106 more rows</code></pre>
<p><em>With this, I wanted to see which Female Marvel Characters had the highest intelligence and Power. From this, it can be seen that Jean Grey and Phoenix have the higher power and intelligence. Jean Grey and Phoenix are actually the same people (Phoenix is Jean Grey’s alias). Based on the movies and comic books I have read, I can definitely see Jean Grey having the most power out of all the Marvel females.</em></p>
</div>
<div id="creating-a-new-column-bmi-and-then-classifying-their-bmi" class="section level4">
<h4>Creating a new column BMI and then classifying their BMI</h4>
<pre class="r"><code>character &lt;- character %&gt;% mutate(BMI = Weight/((Height/100)^2))
character %&gt;% select(Name, Height, Weight, BMI) %&gt;% arrange(BMI)</code></pre>
<pre><code>## # A tibble: 409 x 4
##    Name          Height Weight     BMI
##    &lt;fct&gt;          &lt;dbl&gt;  &lt;int&gt;   &lt;dbl&gt;
##  1 Groot            701      4  0.0814
##  2 Fin Fang Foom    975     18  0.189 
##  3 Galactus         876     16  0.209 
##  4 Longshot         188     36 10.2   
##  5 Cloak            226     70 13.7   
##  6 Snowbird         178     49 15.5   
##  7 Feral            175     50 16.3   
##  8 Venom II         175     50 16.3   
##  9 Binary           180     54 16.7   
## 10 Warbird          180     54 16.7   
## # … with 399 more rows</code></pre>
<pre class="r"><code>character &lt;- character %&gt;% mutate(BMI_class = case_when(BMI &lt; 
    18.5 ~ &quot;Underweight&quot;, BMI &lt; 24.9 ~ &quot;Normal&quot;, BMI &lt; 29.9 ~ 
    &quot;Overweight&quot;, BMI &gt;= 30 ~ &quot;Obese&quot;))

character %&gt;% select(Name, Height, Weight, BMI_class)</code></pre>
<pre><code>## # A tibble: 409 x 4
##    Name              Height Weight BMI_class  
##    &lt;fct&gt;              &lt;dbl&gt;  &lt;int&gt; &lt;chr&gt;      
##  1 A-Bomb               203    441 Obese      
##  2 Abe Sapien           191     65 Underweight
##  3 Abin Sur             185     90 Overweight 
##  4 Abomination          203    441 Obese      
##  5 Adam Strange         185     88 Overweight 
##  6 Agent Bob            178     81 Overweight 
##  7 Agent Zero           191    104 Overweight 
##  8 Air-Walker           188    108 Obese      
##  9 Alan Scott           180     90 Overweight 
## 10 Alfred Pennyworth    178     72 Normal     
## # … with 399 more rows</code></pre>
<p><em>Through this, I created a column for BMI and BMI class (based on BMI). While looking through the data, I saw that there were some character who had a very large weight or height and wanted to see how their BMI classified them. Looking at some of the values for height and weight, there seems to be some error in the dataset. For, instance Groot, the character with the lowest BMI, has a height of 701 cm, but his weight is only 4 kg.</em></p>
</div>
<div id="determining-the-average-intelligence-strength-speed-and-power-of-characters-based-on-their-comic-book-publisher" class="section level4">
<h4>Determining the average Intelligence, Strength, Speed, and Power of characters based on their comic book publisher</h4>
<pre class="r"><code>character %&gt;% group_by(Publisher) %&gt;% summarise(mean_intelligence = mean(Intelligence), 
    mean_strength = mean(Strength), mean_speed = mean(Speed), 
    mean_power = mean(Power)) %&gt;% arrange(mean_intelligence, 
    mean_strength, mean_speed, mean_power)</code></pre>
<pre><code>## # A tibble: 6 x 5
##   Publisher         mean_intelligence mean_strength mean_speed mean_power
##   &lt;fct&gt;                         &lt;dbl&gt;         &lt;dbl&gt;      &lt;dbl&gt;      &lt;dbl&gt;
## 1 Team Epic TV                    1             1          1          0  
## 2 Dark Horse Comics              47.2          35.2       37.6       24.4
## 3 Marvel Comics                  52.5          34.7       31.2       46.6
## 4 Shueisha                       53            90         53.5      100  
## 5 DC Comics                      58.5          36.6       36.1       52.3
## 6 Image Comics                   75            60         50        100</code></pre>
<p><em>I was not expecting to see any association between comic book publisher and the characters intelligence, strength, speed, and power. At a glance, Image Comics seems to produce most intelligent characters, Shueisha produces the speediest and strongest characters, and Image Comics and Shueisha are tied for powerful characters.</em></p>
</div>
</div>
<div id="creating-summary-statistics" class="section level3">
<h3>Creating summary statistics</h3>
<div id="in-this-i-will-determine-the-mean-stadard-deviation-maximum-minimum-and-variance-of-each-of-the-numeric-values-in-the-joined-dataset.-i-will-be-using-pivot_longer-separate-and-pivot_wider-to-create-my-summary-statistic-table" class="section level5">
<h5>In this, I will determine the mean, stadard deviation, maximum, minimum, and variance of each of the numeric values in the joined dataset. I will be using pivot_longer, separate, and pivot_wider to create my summary statistic table</h5>
<pre class="r"><code>summary_table &lt;- character %&gt;% select_if(is.numeric) %&gt;% summarise_all(funs(mean, 
    sd, max, min, var))
summary_table &lt;- summary_table %&gt;% pivot_longer(1:length(summary_table), 
    names_to = &quot;name&quot;, values_to = &quot;value&quot;) %&gt;% separate(name, 
    into = c(&quot;numeric&quot;, &quot;statistic&quot;)) %&gt;% pivot_wider(names_from = &quot;statistic&quot;, 
    values_from = &quot;value&quot;)
summary_table %&gt;% arrange(mean)</code></pre>
<pre><code>## # A tibble: 10 x 6
##    numeric       mean    sd   max     min    var
##    &lt;chr&gt;        &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;
##  1 Speed         32.5  24.3  100   1        591.
##  2 Strength      35.2  32.9  100   1       1082.
##  3 BMI           40.6 146.  2510.  0.0814 21454.
##  4 Power         47.9  32.3  100   0       1041.
##  5 Durability    50.6  34.2  120   1       1168.
##  6 Intelligence  53.7  29.0  100   1        844.
##  7 Combat        53.7  30.2  101   1        912.
##  8 Weight       115.  110.   900   4      12203.
##  9 Height       188.   63.0  975  15.2     3975.
## 10 Total        274.  147.   581   5      21678.</code></pre>
<p><em>In order to tidy this summary table, I first did a pivot_longer, which caused all of the summary stat names to be in one column in this format type_stat (ex. “height_mean”). I did a separate to separate the type and stat type into two columns. Lastly, I did a pivot wider to get all the stats to be column names. There is nothing that interesting from this table.</em></p>
</div>
<div id="here-i-am-going-to-group-by-gender-and-alignment-and-get-the-mean-of-the-height-weight-intelligence-strength-and-total." class="section level4">
<h4>Here I am going to group by Gender and Alignment and get the mean of the Height, Weight, Intelligence, Strength, and Total.</h4>
<pre class="r"><code>character %&gt;% group_by(Gender, Alignment) %&gt;% summarise(mean(Intelligence), 
    mean(Strength), mean_total = mean(Total), n()) %&gt;% arrange(mean_total)</code></pre>
<pre><code>## # A tibble: 9 x 6
## # Groups:   Gender [3]
##   Gender Alignment `mean(Intelligence)` `mean(Strength)` mean_total `n()`
##   &lt;fct&gt;  &lt;fct&gt;                    &lt;dbl&gt;            &lt;dbl&gt;      &lt;dbl&gt; &lt;int&gt;
## 1 -      &quot;good&quot;                    29.1             14.5       141.    11
## 2 -      &quot;bad&quot;                     38               27         142.     2
## 3 Female &quot;bad&quot;                     48.8             26.4       217.    20
## 4 Male   &quot;&quot;                        42               29.7       221.     3
## 5 Female &quot;good&quot;                    50.2             29.6       246.    95
## 6 Female &quot;neutral&quot;                 50               10         261      1
## 7 Male   &quot;good&quot;                    54.6             36.7       286.   178
## 8 Male   &quot;bad&quot;                     59.4             41.7       301.    90
## 9 Male   &quot;neutral&quot;                 64.7             52.8       379.     9</code></pre>
</div>
<div id="i-am-going-to-group-by-race-and-determine-the-proportion-of-the-group-that-is-good" class="section level4">
<h4>I am going to group by Race and determine the proportion of the group that is good</h4>
<pre class="r"><code>race_good &lt;- character %&gt;% group_by(Race) %&gt;% summarise(proportion_good = mean(Alignment == 
    &quot;good&quot;), count = n())

race_good</code></pre>
<pre><code>## # A tibble: 40 x 3
##    Race       proportion_good count
##    &lt;fct&gt;                &lt;dbl&gt; &lt;int&gt;
##  1 -                    0.701   164
##  2 Alien                0.4       5
##  3 Amazon               1         2
##  4 Android              0.333     6
##  5 Animal               1         1
##  6 Asgardian            0.75      4
##  7 Atlantean            0.8       5
##  8 Bizarro              0         1
##  9 Bolovaxian           1         1
## 10 Clone                1         1
## # … with 30 more rows</code></pre>
<pre class="r"><code>race_good %&gt;% filter(proportion_good == min(proportion_good))</code></pre>
<pre><code>## # A tibble: 9 x 3
##   Race            proportion_good count
##   &lt;fct&gt;                     &lt;dbl&gt; &lt;int&gt;
## 1 Bizarro                       0     1
## 2 Cosmic Entity                 0     1
## 3 Czarnian                      0     1
## 4 Frost Giant                   0     1
## 5 Human / Altered               0     1
## 6 Korugaran                     0     1
## 7 Metahuman                     0     1
## 8 Neyaphem                      0     1
## 9 Zombie                        0     1</code></pre>
<pre class="r"><code>race_good %&gt;% filter(proportion_good == max(proportion_good))</code></pre>
<pre><code>## # A tibble: 17 x 3
##    Race            proportion_good count
##    &lt;fct&gt;                     &lt;dbl&gt; &lt;int&gt;
##  1 Amazon                        1     2
##  2 Animal                        1     1
##  3 Bolovaxian                    1     1
##  4 Clone                         1     1
##  5 Demi-God                      1     2
##  6 Flora Colossus                1     1
##  7 Human-Kree                    1     1
##  8 Human-Vuldarian               1     1
##  9 Icthyo Sapien                 1     1
## 10 Inhuman                       1     3
## 11 Kakarantharaian               1     1
## 12 Martian                       1     1
## 13 Mutant / Clone                1     1
## 14 Saiyan                        1     1
## 15 Tamaranean                    1     1
## 16 Ungaran                       1     1
## 17 Vampire                       1     1</code></pre>
<p><em>The purpose of this was to determine what proportion of a ace was classified as good. I also put the count of each race so that we would know how many characters represent that Race. A lot of the Races classified as all good (1) or all bad (0), seem to have very few people in their group.</em></p>
</div>
<div id="i-am-going-to-group-by-gender-and-get-the-number-in-each-gender" class="section level4">
<h4>I am going to group by Gender and get the number in each gender</h4>
<pre class="r"><code>character %&gt;% group_by(Gender) %&gt;% summarise(n())</code></pre>
<pre><code>## # A tibble: 3 x 2
##   Gender `n()`
##   &lt;fct&gt;  &lt;int&gt;
## 1 -         13
## 2 Female   116
## 3 Male     280</code></pre>
<p><em>I am not that surprised from these results. I expected there to be much more males characters than female characters in the Marvel Universe.</em></p>
</div>
</div>
</div>
<div id="visualizations" class="section level2">
<h2>Visualizations</h2>
<div id="correlation-heat-map" class="section level3">
<h3>Correlation Heat Map</h3>
<pre class="r"><code>cor_characters &lt;- character %&gt;% select_if(is.numeric) %&gt;% cor(use = &quot;pair&quot;)
cor_characters &lt;- cor_characters %&gt;% as.data.frame %&gt;% rownames_to_column(&quot;var1&quot;) %&gt;% 
    pivot_longer(-1, names_to = &quot;var2&quot;, values_to = &quot;correlation&quot;)

cor_characters %&gt;% ggplot(aes(var1, var2, fill = correlation)) + 
    geom_tile() + geom_text(aes(label = round(correlation, 2)), 
    color = &quot;black&quot;, size = 4) + theme(axis.text.x = element_text(angle = 90, 
    hjust = 1)) + coord_fixed() + scale_fill_gradient2(low = &quot;red&quot;, 
    mid = &quot;white&quot;, high = &quot;blue&quot;)</code></pre>
<p><img src="/project/project1_files/figure-html/unnamed-chunk-15-1.png" width="672" style="display: block; margin: auto;" />
<em>The strongest relationships seem to be between Total column and all of the things that add up to make the total column (such as Combat, Durability, Height, Intelligence, Power, Speed, and Strength) which makes sense. Another thing that is interesting is the BMI seems to have a very low and even negative correlation (with Speed and Height) with all of the character statististics. BMI’s negative relationship with Height makes sense though because of the way BMI is calculated. This is also seen with Height and Weight.</em></p>
<div id="determining-how-weights-differ-in-each-of-the-different-races." class="section level4">
<h4>Determining how weights differ in each of the different Races.</h4>
<pre class="r"><code>character %&gt;% ggplot(aes(Race, Weight, fill = Total)) + geom_bar(stat = &quot;summary&quot;, 
    fun = mean) + theme(axis.text.x = element_text(angle = 90, 
    hjust = 1)) + scale_y_continuous(breaks = seq(-100, 500, 
    50)) + ggtitle(&quot;Relationship between the different Races and the Average Weights&quot;) + 
    ylab(&quot;Weight (kg)&quot;)</code></pre>
<p><img src="/project/project1_files/figure-html/unnamed-chunk-16-1.png" width="672" style="display: block; margin: auto;" />
<em>From this graph, its seems like New God Race has the largest weight, whereas the Flora Colossus Race has the lowest weight. There also does not seem to be any significant relationship with Total, which makes sense from the correlation heat map created. </em></p>
</div>
</div>
<div id="visualizing-the-distribution-of-total-statistics-in-each-of-the-different-alignments." class="section level3">
<h3>Visualizing the Distribution of Total statistics in each of the different Alignments.</h3>
<pre class="r"><code>character %&gt;% filter(Alignment != &quot;&quot;) %&gt;% ggplot(aes(Alignment, 
    Total)) + geom_boxplot() + geom_jitter(alpha = 0.4, aes(color = Gender)) + 
    ggtitle(&quot;Alignment of Characters Vs. their Total statistics&quot;)</code></pre>
<p><img src="/project/project1_files/figure-html/unnamed-chunk-17-1.png" width="672" style="display: block; margin: auto;" />
<em>The most interesting aspect of this graph is that both bad and good characters seem to have almost the same distribution, which is very surprising. I would have thought that the good characters would at least have a median total higher than that of the bad characters. Also, there does not seem to be a any relationship with Gender and Total and Alignment.</em></p>
</div>
</div>
<div id="dimensionality-reduction---pam-clustering" class="section level2">
<h2>Dimensionality Reduction - PAM clustering</h2>
<div id="process-the-data-by-chosing-the-numerical-variables-i-want-to-analyze-and-scaling-them" class="section level4">
<h4>Process the data by chosing the numerical variables I want to analyze and scaling them</h4>
<pre class="r"><code>library(cluster)

pam_dat &lt;- character %&gt;% select(BMI, Intelligence, Strength, 
    Speed, Power) %&gt;% scale</code></pre>
</div>
<div id="picking-the-best-number-of-clusters" class="section level4">
<h4>Picking the best number of clusters:</h4>
<pre class="r"><code>sil_width &lt;- vector()
for (i in 2:10) {
    pam_fit &lt;- pam(pam_dat, k = i)
    sil_width[i] &lt;- pam_fit$silinfo$avg.width
    
    
}
ggplot() + geom_line(aes(x = 1:10, y = sil_width)) + scale_x_continuous(name = &quot;k&quot;, 
    breaks = 1:10) + ggtitle(&quot;Choosing the Best K with Silhouette Method&quot;)</code></pre>
<p><img src="/project/project1_files/figure-html/unnamed-chunk-19-1.png" width="672" style="display: block; margin: auto;" />
<em>Based on the average Silhouette width, the best number of cluster to choose is 2. This is because k=2, gives us the highest average silhoutte width. However, I am going to go with 3 clusters so that there are more groupings to work with.</em></p>
</div>
<div id="use-only-numerics-and-running-cluster-analysis" class="section level4">
<h4>Use only numerics and running cluster Analysis</h4>
<pre class="r"><code>pam_dat &lt;- character %&gt;% select(BMI, Intelligence, Strength, 
    Speed, Power) %&gt;% scale
pam_analysis &lt;- pam_dat %&gt;% pam(k = 3)
pam_analysis</code></pre>
<pre><code>## Medoids:
##       ID         BMI Intelligence   Strength      Speed       Power
## [1,]  22  0.01385592     0.319965  1.3611490  0.7182145  0.52965932
## [2,]  81 -0.06876848     0.319965 -0.4936386  0.1010068 -0.05926364
## [3,] 369 -0.11225679    -1.814650 -1.0409530 -1.2979975 -1.48507713
## Clustering vector:
##   [1] 1 2 1 1 3 3 2 1 1 2 1 3 2 2 1 1 2 2 1 1 1 1 3 2 1 1 2 2 1 3 2 3 2 2 2 2 2
##  [38] 2 2 2 2 2 3 2 2 1 1 2 3 2 1 1 1 2 2 2 2 2 2 3 2 2 2 2 2 2 2 1 1 3 1 3 2 2
##  [75] 3 2 2 1 2 2 2 3 1 3 1 1 1 3 2 3 1 2 2 3 3 3 2 1 3 2
##  [ reached getOption(&quot;max.print&quot;) -- omitted 309 entries ]
## Objective function:
##    build     swap 
## 1.192190 1.136586 
## 
## Available components:
##  [1] &quot;medoids&quot;    &quot;id.med&quot;     &quot;clustering&quot; &quot;objective&quot;  &quot;isolation&quot; 
##  [6] &quot;clusinfo&quot;   &quot;silinfo&quot;    &quot;diss&quot;       &quot;call&quot;       &quot;data&quot;</code></pre>
</div>
<div id="visualize-and-interpret-clusters" class="section level4">
<h4>Visualize and Interpret Clusters</h4>
<pre class="r"><code>pam_dat &lt;- pam_dat %&gt;% as.data.frame()

cluster_df &lt;- pam_dat %&gt;% mutate(cluster = as.factor(pam_analysis$clustering))
library(GGally)
ggpairs(cluster_df, columns = 1:5, aes(color = cluster))</code></pre>
<p><img src="/project/project1_files/figure-html/unnamed-chunk-21-1.png" width="672" style="display: block; margin: auto;" /></p>
<div id="determine-if-clusters-could-be-broken-down-into-alignment-type" class="section level5">
<h5>Determine if clusters could be broken down into Alignment type</h5>
<pre class="r"><code>character %&gt;% mutate(cluster = factor(pam_analysis$clustering)) %&gt;% 
    filter(Alignment != &quot;&quot;) %&gt;% group_by(cluster, Alignment) %&gt;% 
    summarise(n = n()) %&gt;% mutate(prop = n/sum(n, na.rm = T)) %&gt;% 
    pivot_wider(-n, names_from = Alignment, values_from = prop)</code></pre>
<pre><code>## # A tibble: 3 x 4
## # Groups:   cluster [3]
##   cluster   bad  good neutral
##   &lt;fct&gt;   &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;
## 1 1       0.292 0.677  0.0308
## 2 2       0.278 0.694  0.0287
## 3 3       0.239 0.761 NA</code></pre>
<p><em>Interpretation: From both the visualization and the above matrix, there does not seem to be a great distinction between the clusters. Looking at the BMI visualization, there does not seem to be any distinct clusters- just one big blob. For the other variables there is slight clustering but they all seemed meshed together, probably giving them a low between sums of squares (BSS). The within sums of squares is also probably high because each cluster seems to be very spread out. There also does not seem to be a clear division for Alignment when looking at the proportion table. All three clusters seem to have about the same proportion of good and bad characters in it</em></p>
</div>
</div>
<div id="discuss-goodness-of-fit" class="section level4">
<h4>Discuss goodness of fit</h4>
<pre class="r"><code>pam_analysis$silinfo$avg.width</code></pre>
<pre><code>## [1] 0.4074043</code></pre>
<p><em>The average silhoutte width of this PAM analysis is around 0.41 which makes this model slightly weak. This could be because the distance between the points within each cluster is slightly high or that the distance between each cluster is low. From the visualization plots above, it seems that the between cluster distance is not the clearest. </em></p>
</div>
</div>
<div id="conclusion" class="section level2">
<h2>Conclusion</h2>
<div id="both-marvel-datasets-seemed-to-have-a-lot-of-observations.-by-joining-the-two-datasets-a-lot-of-good-information-was-collected.-i-liked-seeing-the-correlation-between-the-variables.-but-my-favorite-part-about-this-project-was-being-able-to-bring-in-my-love-for-the-marvel-universe-and-seeing-some-of-the-associations-i-saw-through-my-years-of-watchingreading-marvel." class="section level5">
<h5>Both marvel datasets seemed to have a lot of observations. By joining the two datasets, a lot of good information was collected. I liked seeing the correlation between the variables. But my favorite part about this project was being able to bring in my love for the Marvel Universe and seeing some of the associations I saw through my years of watching/reading Marvel.</h5>
</div>
</div>
